#
#-- Copyright (C) 2019 dz <dingzhong110@gmail.com>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for Auto DNS for dnspod-MultiDns
LUCI_DEPENDS:= +bash +curl
PKG_NAME:=luci-app-dnspod-MultiDns
PKG_VERSION:=1.14

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
